obj-$(CONFIG_OPLUS_DEVICE_INFO)      += device_info/
obj-$(CONFIG_OPLUS_CHG)             += misc/
obj-$(CONFIG_HORAE_THERMAL_SHELL)    += thermal/
obj-y                                += sensor/
obj-$(CONFIG_OPLUS_SYSTEM_KERNEL)    += system/
